-- Historical migration tombstone.
-- The obsolete found_items schema is superseded by the 20260826133434 core baseline.
-- Keep this version so local migration history stays aligned with the linked project.
